### ISSUE TITLE
Parameter model should be constructible to enable reference parameters

### ISSUE THREAD

**Issue by arturdzm** [eclipse/microprofile-open-api#123]
Example:

```
parameters:
 - $ref: '#/components/paramters/MyParam'
 - $ref: '#/components/paramters/MyParam2'

OASFactory.createObject(Parameter.class).ref("myParam2")

```

**Comment by arthurdm** [comment]
Although it's true that the above code seems reasonable for the usage of `ref`, I don't necessarily agree that we should make `Parameter` a constructible model because that would mean someone could build `OASFactory.createObject(Parameter.class)` (i.e. a parameter without a specified `in`) and give that back via the filter or model reader.  

I vote that we keep the current models, and if someone wants to build a Parameter reference just use the instance of the target reference, for example:  `OASFactory.createObject(HeaderParameter.class).ref("myParam2")`.

The javadoc of `ref` already states that its usage prevents any of the other methods from the class from being valid, so we're ok.

@EricWittmann - thoughts on this, as you have been building some models?

**Comment by EricWittmann** [comment]
I agree with Arthur with an H. 😀

**Comment by arthurdm** [comment]
Cool - closing this one then.  @arturdzm - thanks for bringing this up.  It was a valid discussion.

**Comment by arturdzm** [comment]
Sure, sounds good to me.
