### ISSUE TITLE
TCK don't use CDI

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#227]
MP enforces CDI to be a central point but TCK don't decorate with @Dependent (or any scope) the beans (in particular application) so it is not MP compatible in terms of JAXRS deployment.

A trivial fix can be to add a beans.xml in WEB-INF.

**Comment by arthurdm** [comment]
The JAXRS applications that the TCK uses are perfectly compatible with MP, as JAXRS is part of MP.  Yes, CDI is also part of MP, but you don't have to use CDI to be MP compatible.

**Comment by rmannibucau** [comment]
This is plain wrong. JAXRS without cdi is defined in an EE container which has other IoC than CDI. MP only has CDI so an MP app or extension spec relies on CDI by design.

**Comment by EricWittmann** [comment]
@kenfinnigan Any thoughts on this?

**Comment by kenfinnigan** [comment]
I think @rmannibucau and @arthurdm are both right.

While the current TCK does validate things correctly, as there's nothing saying that an MP application must use CDI to be an MP application, it would certainly be beneficial to include TCK tests that verify the same behavior whether a class is a CDI Bean or not

**Comment by EricWittmann** [comment]
OK thanks Ken.  So it seems to me that if a JAX-RS app **without** CDI is a valid MP application, then the TCK is currently fine.

@arthurdm - I think it's your decision whether you want to open a separate issue to **add** another TCK test that validates the openapi output is the same whether a JAX-RS app is CDI annotated or not.

**Comment by arthurdm** [comment]
thanks for the feedback guys.  

I think that adding an extra TCK tests for this would only be interesting if there were a commonly used CDI annotation that modifies the resulting `openapi` document.

**Comment by struberg** [comment]
Folks, MP mandatory requires CDI. So I really don't understand that argument.

I think the point is that the class has to be in a bean archive and must be a 'Managed Bean'. At least according to the EE umbrella spec afair. Even in EE it must be either a @Stateless bean or a CDI bean, isn't?
What's wrong with just adding an empty META-INF/beans.xml or e.g. @ApplicationScoped to that resources? 
Will get ignored in Spring but is a valid resource in EE (and thus MP) hindsight

**Comment by rmannibucau** [comment]
Side Note: all but schema on model annotations can be modified by cdi by design, i know only geronimo impl supports it but it is a bug in other impls and a violation of cdi support.

Also mp without cdi is plain undefined in the spec and doesnt make any sense since it also means you dont have any way to register prover etc so not a single user can rely on it. CDI is mandatory for MP by construction and it was intended and why MP was done outside EE: make cdi the central piece of the platform.

**Comment by arthurdm** [comment]
@struberg - are you saying a JAXRS application that doesn't use CDI is not a valid MP application?

**Comment by struberg** [comment]
Oki, did look it up. Please correct me if you think I'm wrong.

JAX-RS-2.1 §2.3
* 2.3.1: SE environment: code has to call RuntimeDelegate#createEndpoint -> no auto scanning
* 2.3.2: Servlet: web.xml with servlet-name javax.ws.rs.core.Application or register your own Application as servlet -> no auto scanning. Apart from that Servlet is _not_ part of MP. So 2.3.2 doesn't apply at all.
* 2.3.3 'Other Container' -> defer to EE umbrella spec which defines Servlet way + managed beans (EE.6.14). In Table EE.5-1 you also find funny restrictions "Resource and  CDI injection is supported only in JAX-RS components managed by CDI"

Since we are neither Full EE nor officially have Servlets: how to pick up Resource endpoints and JAX-RS Applications at all if not making them CDI beans?

**Comment by rmannibucau** [comment]
Yep exactly, none of the discovery applies to MP except the CDI based one so MP requires CDI by design (this is how it was founded actually).

**Comment by arthurdm** [comment]
I agree we could  **add** a test that uses CDI, but my main issue with this discussion is the indication that a JAXRS application that doesn't use CDI is not a valid MP application.  I don't think that's right at all.  MP brings in JAXRS and CDI as separate specs - you can use one, or the other, or both.     Yes the path we want to stir folks is to combine them, and use MP Config too, but you are not required to use all of the MP specs to be an MP app.  

It's a slippery slope if we all just start interpreting what MicroProfile means in terms of the specs it brings.   Where is the MP documentation that restricts JAX-RS?

**Comment by rmannibucau** [comment]
@arthurdm JAXRS spec does by itself as @struberg shown. There is no other portable way to deploy a JAX-RS app without CDI in MP. The best which could be done (but please never do it) is to instantiate each bean with a "newInstance" but it looses all the potential JAX-RS ecosystem since there is no more scanning and autodiscovery, no more injection etc. This would only work for these TCK cause they use mocks and don't integrate with other MP specs. So it is a very particular case and not the MP one. Do you see any alternative which would stay consistent with MP?

**Comment by NottyCode** [comment]
@struberg I've just read the JAX-RS 2.1 and EE platform sections you reference and I don't see anything that says you have to use CDI to register endpoints. Perhaps it is elsewhere, but JAX-RS says what to do in Java SE, what to do in a servlet container and the third section says:

    An implementation MAY provide facilities to host a JAX-RS application in other types
    of container, such facilities are outside the scope of this specification.

two things a) it doesn't point at the EE spec and b) we aren't full EE in MicroProfile so anything it says isn't normative for a microprofile app anyway. I did go and read EE.6.13 and it doesn't mention CDI anywhere (I also checked EE.6.14 of the EE spec and the words are identical).

My conclusion therefore is that probably everyone is applying the Application subclass rules, + the managed bean rules, but that isn't an explicit requirement. 

In terms of the discussion about whether an MP app can do JAX-RS without CDI I fall on the side of yes it can. We need to solve the resolution of registration, but I'd be in favour of allowing JAX-RS without CDI even though CDI is encouraged.

I do think having a TCK test that proves that CDI + JAX-RS works would make sense.

**Comment by rmannibucau** [comment]
@NottyCode this "MAY" part is ok and very good for vendors (we abuse of it in TomEE for instance) but this is not usable to write any TCK since it is not a "MUST". CDI support is a "MUST" of MP so CDI is reliable for TCK, not the other way around.

**Comment by struberg** [comment]
@NottyCode of course the JAX-RS spec doesn't point to EE. But the EE umbrella spec references and 'enhances' the JAX-RS spec.
And true, we are not _full_ EE. But MicroProfile is a subset profile of EE. So this is the closest we can get. Anything else is just a _MAY_ as you already mentioned. And thus we cannot rely on it to be portable.

Btw, even if `@ApplicationScoped` is a CDI annotation, it will also work with Spring or guice. It works because the JVM spec defines that annotations which are not on the ClassPath are simply ignored.

**Comment by Emily-Jiang** [comment]
I realised I misunderstood the argument. Anyway, what I said earlier remains correct. I disagree the statement of "JAX-RS must use CDI". Check out [this guide](https://openliberty.io/guides/rest-client-java.html) to show how JAX-RS application can function without CDI.

**Comment by struberg** [comment]
@Emily-Jiang you realise that your example is *not* portable? ;)
That's what it is all about! The TCK must only test code which is guaranteed to be portable by some spec!

**Comment by rmannibucau** [comment]
@Emily-Jiang your example is in the "MAY" part of the spec so not portable so out of scope of MP.

**Comment by NottyCode** [comment]
@struberg based on that there is no portable way to do this. There is nothing in MicroProfile that specifies this so by definition it isn't portable, even the CDI approach isn't specified so isn't portable. In terms of a discussion on how to resolve this I don't think this issue is the right place to discuss it. I think it needs a broader discussion with the community.

**Comment by smillidge** [comment]
I thought the whole direction of MicroProfile was to be CDI first. Therefore specs should be built to support CDI first and then if possible support other mechanisms. It seems that is being flipped around in the discussion here.

**Comment by struberg** [comment]
+1 @smillidge 

@NottyCode MicroProfile started as an 'unofficial' JavaEE Profile. Thus the name. And of course it is a JavaEE Profile and like e.g. WebProfile it derives many definitions and features from the full profile. You are fully correct that this is nowhere written down it seems. @jclingan @kwsutter @dblevins  can you confirm? But it still makes a lot of sense to assume so. Otherwise tons of features you rely on would not work. Most of the injection features are actually not defined in the CDI spec. Injection into JAX-RS classes, Servlets etc. 
All this is only defined in the umbrella spec. And we rely on it nonetheless. If you question this then we really would have no single well defined (read: portable) way how to register a REST resource I fear :(
In which case we would push forward and define such a portable way ourselves.

**Comment by NottyCode** [comment]
@smillidge yes, but we have also avoided changing the JAX-RS and CDI specs themselves. When I read the JAX-RS spec I view it as being add @Path to a resource class, and subclass Application using @ApplicationPath. There is no mention of CDI there. I therefore think it is reasonable for someone to write that code and have it work, whether that is through a servlet container or not.

@struberg On that basis I could argue any microprofile implementation must ship servlet based on EE6.13 saying:
 
    The specification describes the deployment of services as a servlet. It must be
    possible to deploy JAX-RS-based applications using this deployment model with
    the servlet-class element of the web.xml descriptor naming the applicationsupplied
    extension of the JAX-RS Application abstract class.

obviously we have been pretty clear in the past that isn't a requirement. There is nothing written down saying 'if in doubt Java EE Platform is normative'

I am not saying we shouldn't close this gap and get it clearly specified, I am saying that to assert that CDI is required by the spec is incorrect since it is unspecified. My view is that we should support the Java code mechanism from JAX-RS even though the spec describes it in terms of a web container because there is nothing in the API a developer would use which is Servlet specific, so nothing bleeds though. I would love to see better integration between CDI and JAX-RS but I think that should be done through the JAX-RS spec in Jakarta EE.

**Comment by struberg** [comment]
well, the WebProfile is also kind of 'restricting' the umbrella EE spec to a list of certain specs. And explicitly excludes all the rest. MicroProfile does the same: we limit the EE profile to at least CDI + JAX-RS + JSON-P (+ JSON-B since mp-2.0). 

Let's take away the point that we need to clarify how JAX-RS Application and Resource detection is intended to work in MicroProfile, ok?

**Comment by rmannibucau** [comment]
Yep, this issue is purely about these particular tck and fixed as sipply as adding an empty beans.xml in meta inf. Then it must be written down at spec level that jaxrs relies on cdi but this is out of scope of this spec to test that.

**Comment by Emily-Jiang** [comment]
I think this needs to be a wide discussion on the MP mailing list to clarify whether we expect JAX-RS working without CDI. If we agree on "JAX-RS has to depend on CDI/JSR330", the TCKs will have to adjust accordingly. An application server is free to support the scenario of "JAX-RS working without CDI". Basically, we need to agree on the baseline.

**Comment by OndrejM** [comment]
> In terms of the discussion about whether an MP app can do JAX-RS without CDI I fall on the side of yes it can.

> When I read the JAX-RS spec I view it as being add @path to a resource class, and subclass Application using @ApplicationPath. There is no mention of CDI there.

@NottyCode, I'm afraid you're not right. If this was true, then Jersey as a reference impl, would autodiscover REST resources in Java SE environment, which isn't true. It requires that resources are defined in a subclass of Application. Try running this example in https://github.com/OndrejM-demonstrations/scaling-with-datagrids/blob/master/01-simple-app/src/main/java/mihalyi/scaling/simple/Main.java after you remove the [ScheduleResource](https://github.com/OndrejM-demonstrations/scaling-with-datagrids/blob/master/01-simple-app/src/main/java/io/microprofile/showcase/schedule/rest/Application.java#L31) registration from the `Application` class - it wouldn't load the `ScheduleResource` resource at all.

The integration of JAX-RS with other EE technologies is specified in the JAX-RS spec in "10.2
Integration with Java EE Technologies". Out of all the options to autodiscover JAX-RS resources, the only one supported in MicroProfile is CDI. The only other way to register the resources is in an Application subclass.

Therefore, a portable MP application should either:
* **turn all JAX-RS resources into CDI beans**
* **register them in a subclass of `Application`**

@Emily-Jiang, @arthurdm, there's really nothing to agree on, the current TCK is clearly non-portable and has more requirements than the JAX-RS spec itself. @rmannibucau and @struberg are right, the TCK needs to be **fixed**.

**Comment by OndrejM** [comment]
By the way, @rmannibucau can you give an example of a test that relies on autodiscovery without CDI? I see that all resources in the TCK are defined by as singletons in an Application subclass, which is portable. Did I miss something?

**Comment by rmannibucau** [comment]
@OndrejM JAXRSApp? :)

**Comment by arthurdm** [comment]
@rmannibucau - I don't understand your point.   JAXRSApp is registered as an `Application` subclass and has its JAX-RS resources defined in a singleton: https://github.com/eclipse/microprofile-open-api/blob/master/tck/src/main/java/org/eclipse/microprofile/openapi/apps/airlines/JAXRSApp.java#L146-L155

what's the issue?

**Comment by rmannibucau** [comment]
@arthurdm the application has no scope and the module has no beans.xml so it is not a CDI bean so it is not a registered application from microprofile stack point of view. Means TCK must not work.

**Comment by arthurdm** [comment]
We discussed this in today's hangout and came to the conclusion that the architectural board needs to guide the decision of "is JAXRS without CDI valid"?   We (MP OpenAPI members) certainly think it is, and it seems others [discussion](https://github.com/eclipse/microprofile/issues/32#issuecomment-398151998) are moving towards a supportive direction that CDI, although strongly recommended, is not required by MP specs.  

Closing this to defer to https://github.com/eclipse/microprofile/issues/32

**Comment by struberg** [comment]
To sum this up (because there seem to still be some confusion left): in the deferred to Architecture issue 32 it was decided to use a CDI first approach. 

That means that the openapi TCK (and other TCKs) should either add a META-INF/beans.xml to those test archives or have the beans explicitly annoated with a CDI Scope or Stereotype (other bean defining annotation [1] would also work but don't make much sense) on the JAX-RS Application and Resources.


[1] https://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#bean_defining_annotations
