### ISSUE TITLE
Clarify behaviour of methods that return list / map

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#240]
A few methods return a list or map of children and are meant to be read-only.  The issue is that we don't specify that in the javadocs, so it's up to interpretation of the vendors - we should clarify these scenarios to avoid inconsistent behaviour.

**Comment by arthurdm** [comment]
We agreed in today's hangout that these maps and lists should be immutable.  This issue will drive the doc updates - and TCK additions.

**Comment by jmini** [comment]
See also discussion of this question in #235 for `getOperations()` in `PathItem` (called `readOperationsMap()` with `1.0.x`). This is a convenience method that returns as one map the 8 Operations for the HTTP verbs (GET, POST, PUT…).

---

But there is even an other cases to consider: the maps that is returned by: `OpenAPI.getPaths()` or by `Components.getSchemas()`

If those maps are also immutable, then I think that you will need to have operation for mutation. Because something like this will no longer be possible:

```java
components.getSchemas().put("Car", carSchema);
```

You need to do:

```
components.addSchema("Car", carSchema);
```

Then some methods to remove elements of each maps are missing.

**Comment by arthurdm** [comment]
good point @jmini - I agree that as part of this work we should ensure that each map has an equivalent `add` and `remove` route to update the collection.

**Comment by jmini** [comment]
This issue requires https://github.com/eclipse/microprofile-open-api/issues/248, so I think that it is a **2.0 feature**.

@arthurdm : can you please update the label?

**Comment by arthurdm** [comment]
Good point.  There is some work that we can do in `1.1` (insert javadoc clarification of immutable maps and add mutating operations where needed) for the existing maps, and in `2.0` when we convert some Map extensions into Map fields we should apply the same concept.   

So it's both `1.1` and `2.0`.   Makes sense?

**Comment by jmini** [comment]
I think we have the same vision, but to sort out the issues. Le me rephrase what I mean.

---

> insert javadoc clarification of immutable maps and add mutating operations where needed

This is part of #248.

---

This issue is about making everything immutable. 

But as long as you have still `Xxxxs extends Map<K,V>` you can not control that `getXxxxs()` in the owner is immutable. Example: `openAPI.getPaths()`

When #248 is solved (the 2.0 version of the solution) we will have `owner.getXxxxs().getYyyys()` w hich returns the immutable Map. Example: `openAPI.getPaths().getPathItems()` and there will also be the mutating operations on path.

**Comment by arthurdm** [comment]
Yup, +1.    In `1.1` we won't be able to block all the mutations from happening (since it extends map), but we can discourage and `deprecate` it via javadoc as a foreshadow of the changes coming in `2.0`.

**Comment by jmini** [comment]
I have opened PR #273 to add the `removeXxxx(Yyyy)` methods.

**Comment by jmini** [comment]
To continue to work on this on the `2.0` branch, the next step is to ensure that the `getXxxx()` returning lists are immutable at TCK level.

Should I write a test that ensures that `getXxxx().add(xxxx)` throw a runtime exception?

If the implementations uses `Collections.unmodifiableList(list)`, then an `java.lang.UnsupportedOperationException` is thrown. But this might already be implementation details.

Any advice?

**Comment by arthurdm** [comment]
hey @jmini - the core idea is that the Map returned does not affect the internal map of the model. 
 Implementations may wish to return a clone, or an unmodifiableList - I would say that's an implementation detail.  

With that in mind, the main check from the TCK would be that `getXxxx().add(xxxx)` does not affect the original Map, so essentially:  `getXxxx().add(xxxx).size() == getXxxx().size() + 1`

**Comment by jmini** [comment]
I have opened PR https://github.com/eclipse/microprofile-open-api/pull/279 to add the removeXxxx(String) methods.

**Comment by jmini** [comment]
Related to this clarification topic, I have opened https://github.com/eclipse/microprofile-open-api/issues/284 to discuss the setter case.

**Comment by jmini** [comment]
This issue can now be closed:

For `1.1` methods were added to manipulate lists and maps:

* lists:  #273
* maps: #279

For `2.0` javadoc and tck were updated to indicates that the maps and lists getters returns a (potentially immutable) copy: #288 

In my opinion nothing more to do here. @arthurdm can you close this?
Thank you a lot.

**Comment by arthurdm** [comment]
yup, thanks @jmini!
