### ISSUE TITLE
Interaction with JAX-RS annotations?

### ISSUE THREAD

**Issue by dvddhln** [eclipse/microprofile-open-api#244]
Hi,
I was wondering if it could be possible either through extending the OASFilter or other fluent builders implementations to interact more with JAX-RS annotations? An example would be defining security schemes with open api annotations and let the filter  pick up on `@RolesAllowed `annotations set on classes or methods. 

BR

David

**Comment by EricWittmann** [comment]
What is the use case for this?  It sounds like you're asking for a generated OpenAPI document that returns different content depending on the user requesting it.  If so, my understanding is that the scoping of OASFilter prohibits that because the OpenAPI document is generated once by the platform and then cached.

**Comment by EricWittmann** [comment]
If I misunderstood you (very possible) then can you give an example?  :)

**Comment by dvddhln** [comment]
I see, well the use case would be to perhaps let the filter be able to pick up on the different roles and have them added to the open api model somehow. Very basic example but it could look like this.

```
@Override
public Operation filterOperation(Operation operation) {
    RolesAllowed allowed = getAnnotation(RolesAllowed.class);
    SecurityRequirement requirement = OASFactory.createObject(SecurityRequirement.class);

    requirement.addScheme("scopes", new ArrayList<>(Arrays.asList(allowed.value())));
    operation.addSecurityRequirement(requirement);
    return operation;
}
```

**Comment by EricWittmann** [comment]
Oh I see now.  I did misunderstand you.  :)

I think this might be something that could be implemented by the vendors as part of annotation scanning.  I don't think it can be part of the filter, since there would be no access to the `RolesAllowed` annotation at the time the filter is executed.

However, this is perhaps a good feature request for [SmallRye OpenAPI](https://github.com/smallrye/smallrye-open-api)!  :)  (shameless plug)  It's something that could be done during scanning of the jax-rs annotations.  

Note that `RolesAllowed` is not actually a JAX-RS annotation - it's more generic than that.  Also, the MP OpenAPI specification doesn't have a lot to say about how vendors should scan annotations to produce the OpenAPI document.  The TCK is a little be prescriptive about it, but even there it's mostly the really obvious stuff.

One question I have with this is what **Security Scheme** should be used when `RollesAllowed` is found?  In your example you create a requirement but don't give it a name.  This will result in an invalid OpenAPI doc.  We'll need to pick one of the defined security schemes.  I can actually see this working pretty well in a vendor implementation - there is likely only a single security scheme defined and when there are multiple, pick the only one that requires scopes.  If there are multiple of those then perhaps do nothing.

Sorry for the stream of conscious response. :)

**Comment by dvddhln** [comment]
Thanks for the input Eric and clarification, really helpful.  Yes perhaps it is up to vendor implementation. I can raise it up in the smallrye-open api to see whether it can be raised as an enhancement.

**Comment by arthurdm** [comment]
good discussion guys, thanks for bringing up this topic @dvddhln 

Having a hook to process the annotations is an interesting concept - we played around with that in WebSphere Liberty with a larger scope where we provided an `OpenAPIReader` interface that get injected with the set of raw `classes` that our scanner picked up and would return the built OpenAPI model.       So your idea is interesting, because a user doesn't need to necessarily know or care about how to process ALL of the annotations, just the ones they want to modify the behaviour.  

If you can keep a layer of APIs / interface hooks during your smallrye prototype, maybe you can bring this back to the spec for a possible integration, maybe in `1.2`?

**Comment by EricWittmann** [comment]
I think an annotation scanner hook is an interesting idea but might need to be vendor specific rather than in the spec.  Not all impls will process annotations the same way.  Although perhaps it could be done in a way that didn't force a specific impl.  In that case it could be pretty cool.

**Comment by arthurdm** [comment]
Discussed in Sept 10 hangout and agreed to pursue this in the Smallrye community via issue https://github.com/smallrye/smallrye-open-api/issues/15
