### ISSUE TITLE
Could a CI job be triggered for open PRs?

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#253]
I think it would be useful to set-up a CI for incoming PRs. Travis-CI or similar.
I can help with the setup, just let me know...

**Comment by arthurdm** [comment]
That would be awesome @jmini - thanks for bringing this up and for volunteering =)

I haven't checked, but I wonder if any of the other microprofile projects have Travis setup.  Since these are owned by the `eclipse` GitHub org, we don't (as committers) have access to all the settings and project admin tools.

@kwsutter @kenfinnigan  do you know?

**Comment by kenfinnigan** [comment]
Instructions on setting up a PR builder are here: https://wiki.eclipse.org/MicroProfile/Continuous_Integration

**Comment by jmini** [comment]
Ok then I must leave it to you guys (I am not an Eclipse Commiter for the MicroProfile project - rights are separated by projects at the Eclipse Fdn)

**Comment by jmini** [comment]
I could verify this with PR #295:

GitHub displays that a Job is running:
<img width="784" alt="GitHub PR" src="https://user-images.githubusercontent.com/1222165/48469108-1e37b480-e7ee-11e8-917f-7dea6b69066c.png">

[Job](https://ci.eclipse.org/microprofile/job/Open-API-pull-requests/1/) in Jenkins:
<img width="357" alt="Jenkins Job" src="https://user-images.githubusercontent.com/1222165/48469109-2132a500-e7ee-11e8-98f5-c94fb72c298d.png">

Closing this issue.

**Comment by arthurdm** [comment]
great work @jmini - thanks!
