### ISSUE TITLE
Automatically hide MP Rest Client operations

### ISSUE THREAD

**Issue by aguibert** [eclipse/microprofile-open-api#289]
Currently I have the following MP Rest Client interface in my application:

```java
@Dependent
@RegisterRestClient
@Path("/")
public interface PlayerService {

    @GET
    @Path("/player/{playerId}")
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(hidden = true) // hide operation from OpenAPI
    public Player getPlayerById(@PathParam("playerId") String id);

    @POST
    @Path("/rank/{playerId}/recordGame")
    @Operation(hidden = true) // hide operation from OpenAPI
    public void recordGame(@PathParam("playerId") String id, @QueryParam("place") int place, @HeaderParam("Authorization") String token);

}
```

By default, these synthetic MP Rest Client operations show up in the MP OpenAPI web UI, so I have to add `@Operation(hidden = true)` to each operation in order to hide them.  If I do not hide them, they cannot be invoked because they are not actual rest endpoints available on the server, they are client-facing model of what some other server's REST API looks like.

To resolve this issue, MP OpenAPI could check if a class that appears to be a JAX-RS endpoint is an interface or if it is annotated with `@RegisterRestClient` it would be automatically excluded.
Alternatively, we could try to ask MP Rest Client to set the `mp.openapi.scan.exclude.classes` system property for rest interfaces known to the component.

CC @arturdzm @andymc12

**Comment by arthurdm** [comment]
Thanks for raising this @aguibert.  I think it's reasonable to add this part to the MP OpenAPI spec: `if it is annotated with @RegisterRestClient it would be automatically excluded.`

**Comment by arthurdm** [comment]
In the Oct 22 hangout we agreed to update the MP OpenAPI 1.1 spec to ignore classes annotated with `@RegisterRestClient`.

**Comment by arthurdm** [comment]
Fixed by PR #320

**Comment by hrsto** [comment]
Hope you don't mind reopening this issue. I have the opposite problem - i have an interface with methods with jax-rs annotations. When i implement this interface it becomes my rest endpoint. But the same interface can function as a microprofile rest client which i can distribute to clients and use from another app - externally. This is very convenient to do so, because you avoid copying yourself and all changes to the rest endpoint come from a single source of truth.

Now i can't document it via openapi, because of this change. Instead of assigning side effects to an annotation from another specification, wouldn't it be better to include a new openapi annotation - `@ExcludeFromOAPI` that can be placed on a type and use that to determine whether openapi runtime will process this type or not. It's much more verbose and clear this way and you avoid the conflict with perfectly usable annotation from another specification.

**Comment by Joseph-Cass** [comment]
I ran into a similar use-case to @hrsto, wanting to exclude certain methods/classes from being processed by OpenAPI
