### ISSUE TITLE
OpenAPI endpoint default mediatype should be json

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#302]
The spec says the default is yaml but to be aligned on the platform and increase interoperability (where javascript will prefer json over yaml) it would be way saner to use json as default IMO.

**Comment by arthurdm** [comment]
hey @rmannibucau - is this a dup of https://github.com/eclipse/microprofile-open-api/issues/228?

**Comment by rmannibucau** [comment]
#228 can imply this one but the opposite is not true.

High level the point is mp should just realy on jaxrs default behavior for serialization of its payloads and not mention any default in the spec. So saying that the answer formatting to /openapi is decided by jaxrs runtime is better than saying anything about json or yaml.

**Comment by EricWittmann** [comment]
I don't have a strong opinion on this, but I can see a reasonable argument for JSON being the default media type for the `/openapi` endpoint.  That said, even if we were to make that change, I would want to keep YAML support **required**.  

I'm suspicious that @rmannibucau is suggesting this change as a wedge to eventually get YAML removed as a requirement, which I would be against.

**Comment by arthurdm** [comment]
ya, while I can see the valid case on sticking with the default jaxrs, this payload (OAS3) certainly carries a distinguished connotation from regular jaxrs payloads - it is meant to either be visualized by humans that are used to OAS3 docs, or fed into code generators.   

The latter can work with JSON or YAML just as easily, as all OpenAPI generators do today.   The former is a tricky one - for years we used JSON as the default Swagger output in Liberty, and it was horrible to look at.   YAML is much easier on the eyes, and what most OAS3 docs I have seen use, so it has a much more natural feel.

I think this is one of the cases that we have to take into consideration the special meaning of the payload, rather than focus on who's producing it (jaxrs).

**Comment by johnament** [comment]
Is there a TCK test that checks the default response presently when the accept header is ommited?

**Comment by rmannibucau** [comment]
To clarify a point: i didnt open this ticket by myself but from a user question so please dont see it related to the other ticket - but i still think it makes sense ;).

Also i can understand the "json was horrible" point except now openapi got tooled and integrated and you dont call that endpoint but a html version and all js widgets dont support yaml so at the end the choice is: do people check yaml (which is almost as bad as json for humans) or an automatic ui? I obviously think that dropping swagger-ui.jar or the dozen of concurrent is trivial and preferred by people cause this is why they use it and why they do openapi at the end.

**Comment by EricWittmann** [comment]
For reference:  https://github.com/eclipse/microprofile-open-api/issues/228#issuecomment-445258344

**Comment by EricWittmann** [comment]
I agree with @johnament that the TCK should test for this.  I believe @ivanjunckes asked this same question somewhere else...

**Comment by EricWittmann** [comment]
@arthurdm you can decide whether to open another issue for updating the TCK vs. use this one?  :)

**Comment by arthurdm** [comment]
Thanks guys.  Opened https://github.com/eclipse/microprofile-open-api/issues/307 for this.
